spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinica
    username: postgres
    password: carlos
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
